export const phone_manufacturers: string[] = [
        "Apple",
        "Samsung",
        "Huawei",
        "Xiaomi",
        "Oppo",
        "Vivo",
        "OnePlus",
        "Sony",
        "LG",
        "Google",
        "Motorola",
        "Nokia",
        "Lenovo",
        "HTC",
        "ASUS",
        "BlackBerry",
        "ZTE",
        "Alcatel",
        "Honor",
        "Realme",
        "TCL",
        "Meizu",
        "Infinix",
        "Micromax",
        "Lava",
        "Panasonic",
        "Sharp",
        "LeEco",
        "Coolpad",
        "Gionee",
        "Symphony",
        "Tecno",
        "Wiko",
        "Kyocera",
        "Yota",
        "Essential",
        "Vertu",
        "CAT",
        "Razer",
        "Poco",
        "Fairphone",
        "Energizer",
        "Acer",
        "Microsoft",
        "Zopo",
        "Vodafone",
        "Black Shark",
        "BQ",
        "Haier",
        "Aspera",
        "Maxwest",
        "MobiWire",
        "Posh Mobile",
        "Yezz",
        "Blu",
        "Ringing Bells",
        "Jolla",
        "Obi Worldphone",
        "Saygus",
        "Wileyfox",
        "Sirin Labs",
        "Turing Phone",
        "Nextbit",
        "Swipe",
        "Elephone",
        "Ulefone",
        "Homtom",
        "UMIDIGI",
        "Doogee",
        "Cubot",
        "Oukitel",
        "Vernee",
        "Nomu",
        "Kenxinda"
    ]
    